#!/bin/bash
fill=0
shrink=1
rotate=0
orient=0
paper=a4
margin=28

prog="${0##*/}"

help="\
$prog: Turn an EPS file in to a PostScript file good for printing. By 
default $prog will print the PS file on an A4 page in portrait mode, 
and will shrink it so that it fits on the page if necessary. Ie, EPS print will
print an EPS file such that it fits on the page.

-f        always fill to max width / height
-l        landscape
-o        orient (rotate to match aspect ratio)
-x        maximize (rotate if necessary) equivalent to -o -f
-m NNNN   specify margin in points (default 28 = 1cm)
-p paper  specify paper type (default a4)"

papersizes="letter 612 792 
legal 612 1008 
statement 396 612 
tabloid 792 1224 
ledger 1224 792 
folio 612 936 
quarto 610 780 
7x9 504 648 
9x11 648 792 
9x12 648 864 
10x13 720 936 
10x14 720 1008 
executive 540 720 
a0 2384 3370 
a1 1684 2384 
a2 1191 1684 
a3 842 1191 
a4 595 842 
a5 420 595 
a6 297 420 
a7 210 297 
a8 148 210 
a9 105 148 
a10 73 105 
b0 2920 4127 
b1 2064 2920 
b2 1460 2064 
b3 1032 1460 
b4 729 1032 
b5 516 729 
b6 363 516 
b7 258 363 
b8 181 258 
b9 127 181 
b10 91 127 
isob0 2835 4008 
isob1 2004 2835 
isob2 1417 2004 
isob3 1001 1417 
isob4 709 1001 
isob5 499 709 
isob6 354 499 
isob7 249 354 
isob8 176 249 
isob9 125 176 
isob10 88 125 
c0 2599 3676 
c1 1837 2599 
c2 1298 1837 
c3 918 1296 
c4 649 918 
c5 459 649 
c6 323 459 
c7 230 323 
dl 312 624"

while [ "${1:0:1}" = "-" ] 
do
	case "$1" in
		-f)
			fill=1
			;;

		-l)
			rotate=1
			;;

		-o)
			orient=1
			;;

		-x)
			orient=1
			fill=1
			;;

		 -m)
		 	margin="$2"
			shift
			;;

		-p)
			paper="$2"
			shift
			;;

		-h)
			echo "$help"
			echo
			echo "Paper sizes are:"
			echo "$papersizes" | awk 'length(a" "$1) > 79 { print a; a=""} {a = a" "$1}'
			exit 0
			;;
		-*)
			echo "$1: unknown option" 1>&2
			echo "$help" 1>&2
			;;
	esac

	shift
done

file="${1:--}"

if [ "$file" == - ]
then
	file="/tmp/epsprint-${$}$RANDOM$UID$RANDOM"
	cat > $file
	tmpfile=1
fi


psize="$(echo "$papersizes" | grep "$paper")"

fgrep BoundingBox "$file" | awk -v fill=$fill -v orient=$orient -v rotate=$rotate -v shrink=$shrink -v psize="$psize" -v margin="$margin" '
!/atend/{
	
	print "%!PS"
	print "save"
	
	split(psize, size_dim);

	paper_w = size_dim[2]
	paper_h = size_dim[3]

	left=$2
	bottom=$3
	top=$5
	right=$4

	width = right - left
	height = top - bottom


	page_w = paper_w - margin * 2
	page_h = paper_h - margin * 2

	#Translate to the centre of the page
	print paper_w/2, paper_h/2, "translate"

	

	fig_aspect = width / height
	page_aspect = page_w / page_h;
	

	if((!orient && rotate) || (fig_aspect > 1 && orient))
	{
		print "90 rotate"
		tmp = page_w
		page_w = page_h
		page_h = tmp
		page_aspect = 1/page_aspect
	}

	
	if(fig_aspect > page_aspect)
		sc = page_w / width
	else
		sc = page_h / height

	scale = 1

	#Scale if necessary
	if(fill || (sc < 1 && shrink))
		scale = sc

	print scale, scale, "scale"

	#Translate to the bottom left of the diagram
	print -left, -bottom,  "translate"

	#Translate to the centre of the diagram
	print -width/2, -height/2, "translate"
	
	exit
}'

sed -e'/^%/d' "$file"

echo "restore showpage"


if [ x$tmpfile != x ]
then
	rm -f $tmpfile
fi


