#!/bin/bash

trap "exit 0" SIGPIPE

n="`basename $0`"

if [ $# != 2 ]
then
cat << FOO 1>&2
$n: error: incorrect args.
Usage: $n file1 file2

Iterleaves two files. - refres to stdin.
FOO
exit 1 
fi

awk '
1
{ getline < "'"$2"'"}
1' "$1" 
