#!/bin/bash
#Do options...

#options are:
#
# -r 		do less in raw mode
# -f XX		xterm foreground colour
# -b XX		xterm background colour
# -h 		help

p=${0##*/}

help="usage: $p [-r] [-f colour] [-b colour] [-h] [file]
-r          run less in raw mode
-f colour   foreground colour
-b colour   background colour
-h          display this message
-x NUM		expand tabs to NUM spaces	

"

export OPTERR=0


xterm=${XTERM:-"xterm -name XTerm"}

la=
xa="+sb -sl 0"
ex=

argerr=0

a1="${1#-}"

while getopts ":rhf:b:x:" arg
do

	
	a1="${a1#$arg}"
	
	if [ "$OPTARG" != "" ]
	then

		#if we have -o ARG 
		if [ "$a1" = "" ]
		then
			shift
			a1=
		else
			a1=
		fi
	fi

	if [ x"$a1" = x ]
	then
		shift
		a1="${1#-}"
		export OPTIND=1
		:
	fi

	case "$arg"
	in
		x)
			la="$la -x $OPTARG"
			if echo "$OPTARG" | grep -qv '[0-9]'
			then
				[ $argerr = 0 ] && echo "$p: bad arguments." && argerr=1
				echo "-x reqires a number, not gibberish."
			fi
		;;

		r)
			la="${la} -r"
		;;

		f)
			xa="${xa} -fg $OPTARG"
		;;

		
		h)
			echo "$help"
			exit 0
		;;
		
		b)
			xa="${xa} -bg $OPTARG"
		;;

		\?|:)
			[ $argerr = 0 ] && echo "$p: bad arguments." && argerr=1

			case "$OPTARG"
			in
				x|b|f)
					echo "-$OPTARG requires an argument."
				;;
				*)
					echo "-$OPTARG is not a recognised option."
			esac
		;;

		*)
			:
			;;
		
	esac 
done

if [ $argerr != 0 ]
then
	
	echo
	echo "$help"
	exit 1

fi

if [ "$1" = "" ] && tty > /dev/null
then
	echo $p: error: too lazy to page the terminal.
	exit 3
fi


#Cat files in to the fifo if we're on a pipe

fifo=${TMP:-/tmp}/xless.$$$RANDOM$RANDOM$RANDOM$RANDOM.fifo

if [ "$1" = "" ]
then
	
	if ! mkfifo $fifo
	then
		echo "$p: error: couldn't make fifo: $fifo"
		exit 2
	fi
	
	$xterm -title "xless -" $xa -e less $la -f $fifo &

	{
		cat > $fifo ; rm -f $fifo 
	} & 
	
else
	$xterm $xa -e less $la $@ &
fi

