#!/bin/bash
trap "exit 0" SIGPIPE
prog="`basename $0`"

usage="\
Usage:

$prog [file1 [file2 [... ] ] ] 

Differentiates the input
"

if [ "$1" == -h ]
then
	echo "$usage"
	exit 1
fi

awk '
NR>1{print $1-A}
{A=$1}
' "$@"
