#!/usr/bin/awk -f
{
	for(i=1; i <= NF; i++)
	{
		sx[i] += $i
		sxx[i] += $i*$i
		n[i]++
	}
	
	if(NF > maxi)
		maxi=NF
}

END{
	printf "mean = " 

	for(i=1; i <= maxi; i++)
		printf(" " sx[i]/n[i] )
	print ""

	printf "std = "
	for(i=1; i <= maxi; i++)
		printf(" " sqrt(sxx[i]/n[i] - (sx[i]/n[i])^2))
	print ""
}
