#!/usr/bin/awk -f
BEGIN{
	if(nbins=="")
	{
		nbins=20
	}
}

NR==1{ 
	min = $1
	max = $1
}


$1 < min { min = $1 }
$1 > max { max = $1 }

{
	data[NR] = $1
	weight[NR] = $2
}

END{
	for(i in data)
		bins[int(nbins * (data[i]-min)/(max - min))]+=weight[i]

	for(i=0; i < nbins; i++)
		print i*(max-min)/nbins+min, bins[int(i)]+0.
}

